/* NetHack 5.0	permonst.h	$NHDT-Date: 1781973085 2026/06/20 16:31:25 $  $NHDT-Branch: NetHack-5.0 $:$NHDT-Revision: 1.31 $ */
/* Copyright (c) Stichting Mathematisch Centrum, Amsterdam, 1985. */
/*-Copyright (c) Kenneth Lorber, Kensington, Maryland, 2015. */
/* NetHack may be freely redistributed.  See license for details. */

/**
 * @file permonst.h
 * @brief What a species is, as opposed to what an individual creature is.
 *
 * A @c permonst describes a kind of monster -- its attacks, resistances, speed,
 * size, what it is made of, how it behaves. Every gnome lord shares one of these,
 * while each has its own @c monst for hit points and position.
 *
 * The species list itself is generated: the enumeration below is built by
 * including the monster data with a macro defined, so the names and the table
 * cannot disagree.
 *
 * @note Several values are not species but answers about them: @c NON_PM means
 *       "no monster", and @c LEAVESTATUE and the two values below it encode what
 *       a death leaves behind rather than what died.
 * @warning Species at or after @c SPECIAL_PM are never generated randomly and
 *          cannot be polymorphed into, so a random draw must respect that bound
 *          rather than picking across the whole list.
 */

/**
 * @file permonst.h
 * @brief 종이 무엇인지. 개별 생물이 무엇인지와 대비되는 것.
 *
 * @c permonst 는 몬스터의 종류를 기술한다. 공격, 저항, 속도, 크기, 무엇으로 되어 있는지,
 * 어떻게 행동하는지다. 모든 노움 군주가 이것 하나를 공유하며, 각자는 체력과 위치를 위한
 * 자기 @c monst 를 갖는다.
 *
 * 종 목록 자체는 생성된다. 아래 열거는 매크로를 정의한 채 몬스터 데이터를 포함해 만들어
 * 지므로, 이름과 표가 서로 어긋날 수 없다.
 *
 * @note 몇몇 값은 종이 아니라 종에 대한 답이다. @c NON_PM 은 "몬스터 아님"을 뜻하고,
 *       @c LEAVESTATUE 와 그 아래 두 값은 무엇이 죽었는지가 아니라 죽음이 무엇을 남기는지를
 *       나타낸다.
 * @warning @c SPECIAL_PM 이후의 종은 무작위로 생성되지 않으며 변신 대상이 될 수도 없다.
 *          그래서 무작위 추첨은 목록 전체에서 뽑는 대신 그 경계를 지켜야 한다.
 */

#ifndef PERMONST_H
#define PERMONST_H

/**
 * @brief Every species, plus the sentinels that are not species.
 * @note Generated by including the monster data with @c MONS_ENUM defined, so
 *       this list and the table built from the same data stay in step.
 * @warning The negative values below @c NON_PM are used by @c end.c to record
 *          what a death leaves; the existing comment explains why they must
 *          compare unequal to @c LEAVESTATUE.
 */
/**
 * @brief 모든 종과, 종이 아닌 특수값들.
 * @note @c MONS_ENUM 을 정의한 채 몬스터 데이터를 포함해 생성된다. 그래서 이 목록과
 *       같은 데이터로 만든 표가 항상 맞는다.
 * @warning @c NON_PM 아래의 음수 값들은 @c end.c 가 죽음이 무엇을 남기는지 기록하는 데
 *          쓴다. 그것들이 @c LEAVESTATUE 와 같지 않게 비교되어야 하는 이유는 기존 주석에
 *          설명되어 있다.
 */
enum monnums {
#define MONS_ENUM
#include "monsters.h"
#undef MONS_ENUM
        NUMMONS,
        NON_PM = -1,              /* "not a monster" */
        LOW_PM = NON_PM + 1,      /* first monster in mons */
        LEAVESTATUE = NON_PM - 1, /* leave statue instead of corpse;
                                   * there are two lower values assigned
                                   * in end.c so that (x == LEAVESTATUE)
                                   * will test FALSE in bones.c:
                                   *  (NON_PM - 2) for no corpse
                                   *  (NON_PM - 3) for no corpse, no grave */
        HIGH_PM = NUMMONS - 1,
        SPECIAL_PM = PM_LONG_WORM_TAIL  /* [normal] < ~ < [special] */
                /* mons[SPECIAL_PM] through mons[NUMMONS-1], inclusive, are
                   never generated randomly and cannot be polymorphed into */
};

/*     This structure covers all attack forms.
 *     aatyp is the gross attack type (eg. claw, bite, breath, ...)
 *     adtyp is the damage type (eg. physical, fire, cold, spell, ...)
 *     damn is the number of hit dice of damage from the attack.
 *     damd is the number of sides on each die.
 *
 *     Some attacks can do no points of damage.  Additionally, some can
 *     have special effects *and* do damage as well.  If damn and damd
 *     are set, they may have a special meaning.  For example, if set
 *     for a blinding attack, they determine the amount of time blinded.
 */

/**
 * @brief One of a species' attacks: how it strikes and what that does.
 * @note The dice fields do not always mean damage. For an attack whose point is
 *       an effect rather than injury -- blinding, for instance -- they give the
 *       duration instead, as the comment above states.
 * @warning An attack may do no damage at all, or may do damage *and* apply an
 *          effect, so a zero here does not mean the attack is harmless.
 */
/**
 * @brief 종이 지닌 공격 하나. 어떻게 때리고 그것이 무엇을 하는지.
 * @note 주사위 필드가 늘 피해를 뜻하는 것은 아니다. 상해가 아니라 효과가 목적인 공격 --
 *       예컨대 실명 -- 에서는 위의 주석이 밝히듯 지속 시간을 나타낸다.
 * @warning 어떤 공격은 피해를 전혀 주지 않을 수도 있고, 피해를 주면서 *동시에* 효과까지
 *          적용할 수도 있다. 여기가 0이라는 것이 무해하다는 뜻은 아니다.
 */
struct attack {
    uchar aatyp;
    uchar adtyp, damn, damd;
};

/**
 * @brief How many attacks a single species may have.
 * @note A fixed array rather than a list, so unused slots are present and must be
 *       recognized as empty rather than iterated blindly.
 */
/**
 * @brief 하나의 종이 가질 수 있는 공격의 개수.
 * @note 목록이 아니라 고정 배열이다. 그래서 쓰이지 않는 자리가 존재하며, 무턱대고
 *       순회하는 대신 비어 있음을 알아보아야 한다.
 */
/*     Max # of attacks for any given monster.
 */

#define NATTK 6

#ifndef ALIGN_H
#include "align.h"
#endif
#include "monattk.h"
#include "monflag.h"

struct permonst {
    const char *pmnames[NUM_MGENDERS];
    const enum monnums pmidx;   /* mons array index aka PM_ identifier */
    char mlet;                  /* symbol */
    schar mlevel,               /* base monster level */
        mmove,                  /* move speed */
        ac,                     /* (base) armor class */
        mr;                     /* (base) magic resistance */
    aligntyp maligntyp;         /* basic monster alignment */
    unsigned short geno;        /* creation/geno mask value */
    struct attack mattk[NATTK]; /* attacks matrix */
    unsigned cwt;               /* weight of corpse */
    unsigned short cnutrit;     /* its nutritional value */
    uchar msound;               /* noise it makes (6 bits) */
    uchar msize;                /* physical size (3 bits) */
    uchar mresists;             /* resistances */
    uchar mconveys;             /* conveyed by eating */
    unsigned long mflags1,      /* boolean bitflags */
        mflags2;                /* more boolean bitflags */
    unsigned short mflags3;     /* yet more boolean bitflags */
    uchar difficulty;           /* toughness (formerly from  makedefs -m) */
    uchar mcolor;               /* color to use */
};

#define NORMAL_SPEED 12

extern NEARDATA struct permonst mons[NUMMONS + 1]; /* the master list of
                                                    * monster types */

#endif /* PERMONST_H */
