/* NetHack	5.0	sym.h	$NHDT-Date: $ $NHDT-Branch: $ $NHDT-Revision: $ */
/*      Copyright (c) 2016 by Pasi Kallinen              */
/* NetHack may be freely redistributed.  See license for details. */

/**
 * @file sym.h
 * @brief What each thing on the map looks like, and how a player may change it.
 *
 * The map is drawn as characters even in tile mode, because a tile is chosen from
 * the same identity a character would have shown. This file names those identities:
 * one for every monster class, every piece of terrain and furniture, every effect.
 *
 * The lists themselves are not written out here. They come from defsym.h, which is
 * read repeatedly with a different macro defined each time, so that one description
 * of a symbol produces the enumerator, the default character, the colour and the
 * name a player would type -- and they cannot drift apart.
 *
 * A player may replace any of it. A symbol set is a named collection of such
 * replacements, and customizations layer on top of a set, which is why they are
 * kept as a list of individual changes rather than a second full table.
 *
 * @note The @c is_cmap_* tests are range comparisons, so the terrain enumerators are
 *       grouped by kind and their order is part of the interface.
 * @warning @c symset_handling_types must stay in step with the handler name strings
 *          in drawing.c; they are matched by position.
 */

/**
 * @file sym.h
 * @brief 지도 위의 각 사물이 어떻게 보이는지, 그리고 플레이어가 그것을 바꾸는 방법.
 *
 * 타일 모드에서도 지도는 문자로 그려진다. 타일이 문자가 나타냈을 것과 같은 정체성에서 골라지기
 * 때문이다. 이 파일은 그 정체성들에 이름을 붙인다. 몬스터 계열마다, 지형과 설비마다, 효과마다
 * 하나씩.
 *
 * 목록 자체는 여기에 적혀 있지 않다. defsym.h 에서 오며, 그 파일은 매번 다른 매크로를 정의한 채
 * 반복해서 읽힌다. 그래서 심볼 하나에 대한 하나의 기술이 열거자, 기본 문자, 색, 플레이어가 입력할
 * 이름을 모두 만들어 내고, 그것들이 서로 어긋날 수 없다.
 *
 * 플레이어는 그 전부를 교체할 수 있다. 심볼 세트는 그런 교체를 모아 이름 붙인 것이고, 사용자
 * 지정은 세트 위에 겹쳐진다. 그래서 두 번째 전체 표가 아니라 개별 변경의 목록으로 보관된다.
 *
 * @note @c is_cmap_* 검사들은 범위 비교다. 그래서 지형 열거자는 종류별로 묶여 있고 그 순서가
 *       인터페이스의 일부다.
 * @warning @c symset_handling_types 는 drawing.c 의 핸들러 이름 문자열과 보조를 맞춰야 한다.
 *          위치로 대응된다.
 */

#ifndef SYM_H
#define SYM_H

/*
 * Default characters for monsters.
 */
/**
 * @brief The character each monster class shows by default.
 * @note Generated by reading defsym.h with @c MONSYMS_DEFCHAR_ENUM defined, so the
 *       character and the class it belongs to are written once, in one place.
 */
/**
 * @brief 각 몬스터 계열이 기본으로 보이는 문자.
 * @note @c MONSYMS_DEFCHAR_ENUM 를 정의한 채 defsym.h 를 읽어 생성된다. 그래서 문자와 그것이
 *       속한 계열이 한 곳에 한 번만 적힌다.
 */
/* clang-format off */
enum mon_defchars {
#define MONSYMS_DEFCHAR_ENUM
#include "defsym.h"
#undef MONSYMS_DEFCHAR_ENUM
};
/* clang-format on */

/**
 * @brief The monster classes themselves, as indices rather than characters.
 * @note A monster's class is stored as one of these, so changing what a class looks
 *       like never touches a monster.
 * @warning @c MAXMCLASSES is the count and not a class, so it is one past the last
 *          valid index.
 */
/**
 * @brief 몬스터 계열 자체. 문자가 아니라 색인으로서.
 * @note 몬스터의 계열은 이 값들 중 하나로 저장된다. 그래서 계열의 외형을 바꾸는 일이 몬스터를
 *       건드리는 일은 결코 아니다.
 * @warning @c MAXMCLASSES 는 개수이며 계열이 아니다. 마지막 유효 색인보다 하나 뒤다.
 */
enum mon_syms {
#define MONSYMS_S_ENUM
#include "defsym.h"
#undef MONSYMS_S_ENUM

    MAXMCLASSES  /* number of monster classes */
};

#ifndef MAKEDEFS_C
/**
 * @brief Everything that can occupy a square without being a monster or object:
 *        terrain, doors, stairs, furniture, traps, and beam and explosion effects.
 * @note Grouped by kind on purpose. The @c is_cmap_* tests below ask "is this one of
 *       the walls" by comparing against the ends of a group, so the order of these
 *       enumerators is depended upon and not merely conventional.
 */
/**
 * @brief 몬스터도 물건도 아니면서 칸을 차지할 수 있는 모든 것. 지형, 문, 계단, 설비, 함정,
 *        광선과 폭발 효과.
 * @note 일부러 종류별로 묶여 있다. 아래의 @c is_cmap_* 검사들은 묶음의 양 끝과 비교해 "이것이 벽
 *       중 하나인가"를 묻는다. 그래서 이 열거자들의 순서는 관례가 아니라 의존되는 대상이다.
 */
enum cmap_symbols {
#define PCHAR_S_ENUM
#include "defsym.h"
#undef PCHAR_S_ENUM
    MAXPCHARS
};

/*
 * special symbol set handling types ( for invoking callbacks, etc.)
 * Must match the order of the known_handlers strings
 * in drawing.c
 */

/**
 * @brief Which display convention a symbol set was written for.
 *
 * A set may assume line-drawing characters that only exist under one terminal
 * convention, so the port is told which one rather than guessing from the bytes.
 *
 * @warning Must match the order of the @c known_handlers strings in drawing.c --
 *          the name a player writes is matched to a value by position.
 * @note @c H_MAC is obsolete but kept so that the symbol set listing can skip it,
 *       which is why the values are not compacted.
 */
/**
 * @brief 심볼 세트가 어떤 표시 규약을 위해 작성되었는지.
 *
 * 어떤 세트는 특정 터미널 규약에서만 존재하는 선 그리기 문자를 전제할 수 있다. 그래서 바이트를
 * 보고 추측하는 대신 포트에게 어느 규약인지 알려 준다.
 *
 * @warning drawing.c 의 @c known_handlers 문자열 순서와 일치해야 한다. 플레이어가 적는 이름이
 *          위치로 값에 대응된다.
 * @note @c H_MAC 은 폐기되었지만 심볼 세트 목록에서 건너뛸 수 있도록 남겨 두었다. 값들이 촘촘히
 *       정리되지 않은 이유가 그것이다.
 */
enum symset_handling_types {
    H_UNK = 0,
    H_IBM = 1,
    H_DEC = 2,
    H_CURS = 3,
    H_MAC = 4, /* obsolete; needed so that the listing of available
                * symsets by 'O' can skip it for !MAC_GRAPHICS_ENV */
    H_UTF8 = 5
};

/**
 * @brief One symbol: what it draws as, what it is called, and what colour it takes.
 * @note The explanation is the text shown when the player asks what a character on
 *       the map means, so it is part of the game's vocabulary rather than a comment.
 */
/**
 * @brief 심볼 하나. 무엇으로 그려지는지, 무엇이라 불리는지, 어떤 색을 띠는지.
 * @note 설명문은 플레이어가 지도 위의 문자가 무엇을 뜻하는지 물었을 때 보여지는 글이다. 그래서
 *       주석이 아니라 게임의 어휘에 속한다.
 */
struct symdef {
    uchar sym;
    const char *explanation;
    uchar color;
};

/**
 * @brief Which table a symbol name refers into.
 *
 * A player writing a symbol set names symbols by name, and the same name space
 * covers terrain, object classes and monster classes. This says which of those
 * tables the accompanying index belongs to.
 *
 * @warning The index alone is meaningless -- the same number is a valid index into
 *          all three tables.
 */
/**
 * @brief 심볼 이름이 어느 표를 가리키는지.
 *
 * 심볼 세트를 작성하는 플레이어는 심볼을 이름으로 지칭하며, 하나의 이름 공간이 지형, 물건 계열,
 * 몬스터 계열을 함께 덮는다. 이 값은 딸린 색인이 그 표들 중 어디에 속하는지를 밝힌다.
 *
 * @warning 색인만으로는 의미가 없다. 같은 숫자가 세 표 모두에서 유효한 색인이다.
 */
enum symparse_range {
    SYM_INVALID = 0,
    SYM_CONTROL = 1, /* start/finish markers */
    SYM_PCHAR = 2,   /* index into showsyms  */
    SYM_OC = 3,      /* index into oc_syms   */
    SYM_MON = 4,     /* index into monsyms   */
    SYM_OTH = 5      /* misc                 */
};

/**
 * @brief The name a player writes for a symbol, paired with where it points.
 * @note This is what lets a symbol set file be text: the file names symbols, and
 *       this table turns each name into a table and an index within it.
 */
/**
 * @brief 플레이어가 심볼에 대해 적는 이름과, 그것이 가리키는 곳의 짝.
 * @note 심볼 세트 파일이 텍스트일 수 있는 이유다. 파일은 심볼을 이름으로 적고, 이 표가 각 이름을
 *       표 하나와 그 안의 색인으로 바꾼다.
 */
struct symparse {
    enum symparse_range range;
    int idx;
    const char *name;
};

/**
 * @brief One available symbol set, as offered to the player.
 *
 * Discovered by scanning the symbol file, so the sets are found rather than compiled
 * in -- which is why they form a list whose length is not known in advance.
 *
 * @note A set may declare itself usable only as the main set or only for the Rogue
 *       level, so an incomplete set can still be offered for the role it does cover.
 * @note @c explicitly records that the player chose this set rather than inheriting
 *       it, which decides whether a later default may replace it.
 */
/**
 * @brief 플레이어에게 제시되는 사용 가능한 심볼 세트 하나.
 *
 * 심볼 파일을 훑어 발견되므로, 세트는 컴파일에 포함되는 것이 아니라 찾아지는 것이다. 길이를 미리
 * 알 수 없는 목록을 이루는 이유가 그것이다.
 *
 * @note 세트는 자신이 주 세트로만, 또는 Rogue 레벨용으로만 쓰일 수 있다고 선언할 수 있다. 그래서
 *       불완전한 세트도 자신이 덮는 역할로는 제시될 수 있다.
 * @note @c explicitly 는 플레이어가 이 세트를 물려받은 것이 아니라 직접 골랐음을 기록한다. 나중의
 *       기본값이 그것을 대체할 수 있는지를 정한다.
 */
/* linked list of symsets and their characteristics */
struct symsetentry {
    struct symsetentry *next; /* next in list                         */
    char *name;               /* ptr to symset name                   */
    char *desc;               /* ptr to description                   */
    int idx;                  /* an index value                       */
    enum symset_handling_types handling;      /* known handlers value */
    Bitfield(nocolor, 1);     /* don't use color if set               */
    Bitfield(primary, 1);     /* restricted for use as primary set    */
    Bitfield(rogue, 1);       /* restricted for use as rogue lev set  */
    Bitfield(explicitly, 1);  /* explicit symset set                  */
                              /* 4 free bits */
};

/*
 *
 */

/**
 * @def MAXDCHARS
 * @brief How many of the symbols are terrain, counted from the ends of that group.
 * @note Derived from the enumerators rather than written as a number, so adding a
 *       terrain symbol inside the group updates the count by itself.
 */
/**
 * @def MAXDCHARS
 * @brief 심볼 중 지형인 것의 개수. 해당 묶음의 양 끝에서 계산된다.
 * @note 숫자로 적지 않고 열거자에서 유도한다. 그래서 묶음 안에 지형 심볼을 추가하면 개수가 저절로
 *       갱신된다.
 */
#define MAXDCHARS (S_water - S_stone + 1) /* mapped dungeon characters */
/**
 * @def MAXTCHARS
 * @brief How many trap symbols there are.
 * @note One fewer than the number of trap types, because @c NO_TRAP is the absence of
 *       a trap and has nothing to draw.
 */
/**
 * @def MAXTCHARS
 * @brief 함정 심볼의 개수.
 * @note 함정 종류의 수보다 하나 적다. @c NO_TRAP 은 함정이 없음을 뜻하므로 그릴 것이 없다.
 */
#define MAXTCHARS (TRAPNUM - 1) /* trap chars */
/** @def MAXECHARS
 *  @brief How many symbols belong to beams, blasts and other transient effects. */
/** @def MAXECHARS
 *  @brief 광선, 폭풍, 그 밖의 일시적 효과에 속한 심볼의 개수. */
#define MAXECHARS (S_expl_br - S_vbeam + 1) /* mapped effects characters */
/**
 * @def MAXEXPCHARS
 * @brief The nine symbols an explosion is drawn from.
 * @note Nine because an explosion covers a three by three area and each position --
 *       corner, edge, centre -- is drawn differently.
 */
/**
 * @def MAXEXPCHARS
 * @brief 폭발을 그리는 데 쓰이는 아홉 개의 심볼.
 * @note 폭발이 3×3 영역을 덮고 모서리, 변, 중앙의 각 위치가 다르게 그려지기 때문에 아홉이다.
 */
#define MAXEXPCHARS 9 /* number of explosion characters */

/**
 * @def DARKROOMSYM
 * @brief What an unlit room square looks like, which depends on the level.
 * @note The Rogue level imitates the original game, where an unlit room square was
 *       indistinguishable from solid rock; elsewhere it has its own appearance.
 * @warning Reads the hero's position, so it cannot be used while describing a level
 *          the hero is not on.
 */
/**
 * @def DARKROOMSYM
 * @brief 불이 켜지지 않은 방 칸의 외형. 레벨에 따라 달라진다.
 * @note Rogue 레벨은 원작을 모방한다. 원작에서는 불 없는 방 칸이 단단한 암반과 구별되지 않았다.
 *       다른 곳에서는 그 자신의 외형을 가진다.
 * @warning 영웅의 위치를 읽는다. 그래서 영웅이 있지 않은 레벨을 기술하는 동안에는 쓸 수 없다.
 */
#define DARKROOMSYM (Is_rogue_level(&u.uz) ? S_stone : S_darkroom)

/**
 * @name Symbol group tests
 * @brief Ask which kind a terrain symbol belongs to.
 *
 * Each is a range comparison against the ends of a group in @c cmap_symbols, which
 * is why those enumerators are grouped and ordered deliberately.
 *
 * @warning The argument is evaluated more than once in every one of these, so an
 *          argument with a side effect will have it applied repeatedly.
 * @warning These accept any number. A value that is not a terrain symbol at all will
 *          still answer true or false rather than reporting the mistake.
 * @{
 */
/**
 * @name 심볼 묶음 검사
 * @brief 지형 심볼이 어느 종류에 속하는지 묻는다.
 *
 * 각각은 @c cmap_symbols 안의 한 묶음의 양 끝과 비교하는 범위 검사다. 그 열거자들이 의도적으로
 * 묶이고 정렬된 이유가 이것이다.
 *
 * @warning 이들 모두에서 인자가 한 번 넘게 평가된다. 그래서 부작용이 있는 인자는 그 부작용이 거듭
 *          적용된다.
 * @warning 어떤 숫자든 받는다. 지형 심볼이 전혀 아닌 값도 잘못을 알리지 않고 참이나 거짓으로
 *          답한다.
 * @{
 */
#define is_cmap_trap(i) ((i) >= S_arrow_trap && (i) < S_arrow_trap + MAXTCHARS)
#define is_cmap_drawbridge(i) ((i) >= S_vodbridge && (i) <= S_hcdbridge)
#define is_cmap_door(i) ((i) >= S_vodoor && (i) <= S_hcdoor)
#define is_cmap_wall(i) ((i) >= S_stone && (i) <= S_trwall)
#define is_cmap_room(i) ((i) >= S_room && (i) <= S_darkroom)
#define is_cmap_corr(i) ((i) >= S_corr && (i) <= S_litcorr)
#define is_cmap_furniture(i) ((i) >= S_upstair && (i) <= S_fountain)
#define is_cmap_water(i) ((i) == S_pool || (i) == S_water)
#define is_cmap_lava(i) ((i) == S_lava || (i) == S_lavawall)
#define is_cmap_stairs(i) ((i) >= S_upstair && (i) <= S_brdnladder)
#define is_cmap_engraving(i) ((i) == S_engroom || (i) == S_engrcorr)
/** @} */

/**
 * @brief Symbols that stand for a state of knowledge rather than a thing.
 *
 * A square the hero has not seen, a monster known to be somewhere but not seen, the
 * mark that says "this is your pet" -- none of these is terrain or a monster class,
 * but each needs an appearance the player can change.
 *
 * @note @c SYM_NOTHING and @c SYM_UNEXPLORED differ: one is a square known to hold
 *       nothing, the other a square nothing is known about.
 */
/**
 * @brief 사물이 아니라 앎의 상태를 나타내는 심볼들.
 *
 * 영웅이 보지 못한 칸, 어딘가에 있다고 알지만 보이지 않는 몬스터, "이것은 당신의 애완동물"이라고
 * 알리는 표시. 어느 것도 지형이나 몬스터 계열이 아니지만, 각각 플레이어가 바꿀 수 있는 외형을
 * 필요로 한다.
 *
 * @note @c SYM_NOTHING 과 @c SYM_UNEXPLORED 는 다르다. 하나는 아무것도 없다고 알려진 칸이고,
 *       다른 하나는 아무것도 알려지지 않은 칸이다.
 */
/* misc symbol definitions */
enum misc_symbols {
        SYM_NOTHING = 0,
        SYM_UNEXPLORED = 1,
        SYM_BOULDER = 2,
        SYM_INVISIBLE = 3,
        SYM_PET_OVERRIDE = 4,
        SYM_HERO_OVERRIDE = 5,
        MAXOTHER
};

/*
 * Graphics sets for display symbols
 */
/**
 * @def DEFAULT_GRAPHICS
 * @brief Plain characters, assuming nothing of the terminal.
 * @note The fallback that always works: if a symbol set is unavailable or unreadable,
 *       the map is still drawable.
 */
/**
 * @def DEFAULT_GRAPHICS
 * @brief 평범한 문자. 터미널에 대해 아무것도 전제하지 않는다.
 * @note 항상 통하는 대비책이다. 심볼 세트를 쓸 수 없거나 읽을 수 없어도 지도는 여전히 그릴 수 있다.
 */
#define DEFAULT_GRAPHICS 0 /* regular characters: '-', '+', &c */
/**
 * @brief Which of the loaded symbol sets is being drawn from.
 *
 * Two are live at once because the Rogue level is drawn differently from the rest of
 * the dungeon, so entering it switches which set is current rather than reloading.
 *
 * @warning @c UNICODESET is deliberately given the value of @c NUM_GRAPHICS -- it is
 *          not one of the sets counted by it, so an array sized by @c NUM_GRAPHICS
 *          cannot be indexed with it.
 */
/**
 * @brief 적재된 심볼 세트 중 어느 것으로 그리고 있는지.
 *
 * 두 개가 동시에 살아 있다. Rogue 레벨이 던전의 나머지와 다르게 그려지므로, 그곳에 들어가는 것은
 * 다시 적재하는 것이 아니라 어느 세트가 현재의 것인지를 바꾸는 일이다.
 *
 * @warning @c UNICODESET 은 의도적으로 @c NUM_GRAPHICS 와 같은 값을 가진다. 그것이 세는 세트에
 *          속하지 않으므로, @c NUM_GRAPHICS 크기로 잡은 배열을 이 값으로 색인할 수 없다.
 */
enum graphics_sets {
        PRIMARYSET = 0,       /* primary graphics set        */
        ROGUESET = 1,         /* rogue graphics set          */
        NUM_GRAPHICS,
        UNICODESET = NUM_GRAPHICS
};

enum do_customizations {
       do_custom_none,
       do_custom_colors,
       do_custom_symbols
};

enum customization_types { custom_none, custom_symbols,
    custom_ureps, custom_nhcolor,  custom_count };

/**
 * @brief One player change to a symbol set, expressed as a change rather than a table.
 *
 * Customizations are kept as a list of individual replacements laid over whichever
 * set is loaded. That is what lets a player alter three symbols without having to
 * describe every other one, and what lets the change survive a change of set.
 *
 * There are three kinds because there are three things that can be replaced: the
 * character a symbol draws as, the multi-byte sequence it draws as, and its colour.
 * @{
 */
/**
 * @brief 심볼 세트에 대한 플레이어의 변경 하나. 표가 아니라 변경으로 표현된다.
 *
 * 사용자 지정은 적재된 세트 위에 겹쳐지는 개별 교체의 목록으로 보관된다. 플레이어가 나머지 전부를
 * 기술하지 않고도 심볼 세 개를 바꿀 수 있는 이유이며, 그 변경이 세트 교체를 견디는 이유다.
 *
 * 교체될 수 있는 것이 세 가지이므로 종류도 세 가지다. 심볼이 그려지는 문자, 그려지는 다중 바이트
 * 열, 그리고 색.
 * @{
 */
/**
 * @brief Replace the single character a named symbol draws as.
 * @note Holds the parse entry rather than a bare index, so the change remembers which
 *       table the symbol lives in.
 */
/**
 * @brief 이름 붙은 심볼이 그려지는 단일 문자를 교체한다.
 * @note 맨 색인 대신 파싱 항목을 담는다. 그래서 변경이 그 심볼이 어느 표에 사는지를 기억한다.
 */
struct custom_symbol {
    const struct symparse *symparse;
    unsigned char val;
};
/**
 * @brief Replace what a glyph draws as with a multi-byte sequence.
 * @note Keyed by glyph and not by symbol, because a glyph is the fully resolved thing
 *       being drawn -- this pet, this class of monster -- and a sequence may be chosen
 *       for one without applying to the others.
 */
/**
 * @brief 글리프가 그려지는 것을 다중 바이트 열로 교체한다.
 * @note 심볼이 아니라 글리프로 색인된다. 글리프는 그려지는 대상이 완전히 확정된 것 -- 이 애완동물,
 *       이 몬스터 계열 -- 이고, 열은 그 중 하나에만 고르고 나머지에는 적용하지 않을 수 있다.
 */
struct custom_urep {
    int glyphidx;
    struct unicode_representation u;
};
/**
 * @brief Replace the colour a glyph is drawn in.
 * @note Also keyed by glyph, so recolouring one monster does not recolour its class.
 */
/**
 * @brief 글리프가 그려지는 색을 교체한다.
 * @note 역시 글리프로 색인된다. 그래서 한 몬스터의 색을 바꾸는 일이 그 계열의 색을 바꾸지는 않는다.
 */
struct custom_nhcolor {
    int glyphidx;
    uint32 nhcolor;
};
/** @} */

/**
 * @brief Whichever of the three kinds of change this one is.
 * @warning Nothing here says which member is live. The @c custtype of the owning
 *          @c symset_customization does, so the union must not be read without it.
 */
/**
 * @brief 세 종류의 변경 중 이것이 무엇인지.
 * @warning 여기에는 어느 멤버가 유효한지를 밝히는 것이 없다. 소유하는
 *          @c symset_customization 의 @c custtype 이 그것을 밝히므로, 그것 없이 이 공용체를
 *          읽어서는 안 된다.
 */
union customization_content {
    struct custom_symbol sym;
    struct custom_urep urep;
    struct custom_nhcolor ccolor;
};
/**
 * @brief One change, linked to the next.
 * @note A list rather than an array because the number of changes a player makes is
 *       not known until the configuration has been read.
 */
/**
 * @brief 변경 하나. 다음 것과 이어져 있다.
 * @note 배열이 아니라 목록인 것은, 플레이어가 몇 개를 바꾸는지 설정을 다 읽기 전까지 알 수 없기
 *       때문이다.
 */
struct customization_detail {
    union customization_content content;
    struct customization_detail *next;
};


/**
 * @brief All of one kind of change, belonging to one named symbol set.
 * @note @c custtype is what makes each detail's union readable, so it is held here
 *       once instead of in every detail.
 * @note The tail is kept as well as the head so that appending, which happens once
 *       per line of configuration read, does not walk the list.
 */
/**
 * @brief 이름 붙은 하나의 심볼 세트에 속한, 한 종류의 변경 전부.
 * @note @c custtype 이 각 항목의 공용체를 읽을 수 있게 만드는 것이다. 그래서 항목마다 두지 않고
 *       여기에 한 번 둔다.
 * @note 머리와 함께 꼬리도 보관한다. 설정 한 줄마다 한 번씩 일어나는 덧붙이기가 목록을 훑지 않도록
 *       하기 위함이다.
 */
/* one set per symset_name */
struct symset_customization {
    const char *customization_name;
    int count;
    enum customization_types custtype;
    struct customization_detail *details;
    struct customization_detail *details_end;
};

/**
 * @var defsyms
 * @brief The built-in appearance of every terrain symbol.
 * @note Constant, and never the table actually drawn from -- it is the source the
 *       drawable table is copied from, so a player's changes can always be undone.
 */
/**
 * @var defsyms
 * @brief 모든 지형 심볼의 내장 외형.
 * @note 상수이며, 실제로 그릴 때 쓰이는 표가 결코 아니다. 그릴 때 쓰는 표가 여기서 복사되므로,
 *       플레이어의 변경은 언제든 되돌릴 수 있다.
 */
extern const struct symdef defsyms[MAXPCHARS + 1]; /* defaults */
/**
 * @def WARNCOUNT
 * @brief How many degrees of warning there are.
 * @note Warning shows that something is there and roughly how dangerous, without
 *       identifying it, so the levels are a scale rather than a list of monsters.
 */
/**
 * @def WARNCOUNT
 * @brief 경고의 단계 수.
 * @note 경고는 무언가가 있다는 것과 대략 얼마나 위험한지를 알리되 그것이 무엇인지는 밝히지 않는다.
 *       그래서 단계들은 몬스터의 목록이 아니라 척도다.
 */
#define WARNCOUNT 6 /* number of different warning levels */
/** @var def_warnsyms
 *  @brief The built-in appearance of each warning level. */
/** @var def_warnsyms
 *  @brief 각 경고 단계의 내장 외형. */
extern const struct symdef def_warnsyms[WARNCOUNT];
/**
 * @def SYMHANDLING
 * @brief Ask whether the set currently being drawn from uses a given convention.
 * @param ht one of @c symset_handling_types
 * @note Asks about the current set, which changes on the Rogue level, so the answer is
 *       not fixed for a game.
 */
/**
 * @def SYMHANDLING
 * @brief 현재 그릴 때 쓰는 세트가 주어진 규약을 쓰는지 묻는다.
 * @param ht @c symset_handling_types 중 하나
 * @note 현재 세트에 대해 묻는다. 그 세트는 Rogue 레벨에서 바뀌므로, 답은 한 게임 동안 고정되어
 *       있지 않다.
 */
#define SYMHANDLING(ht) (gs.symset[gc.currentgraphics].handling == (ht))

#endif /* !MAKEDEFS_C */
#endif /* SYM_H */

